### ISSUE TITLE
Correction des anomalies

### ISSUE THREAD

**Issue by StyveLioumba** [Technostrea/technostrea.com#13]
- [x] #14
- [x]  Retirer le bouton contactez nous dans la page à-propos 
- [x]  Ponctuation et linéarité du texte

**Comment by espery17** [comment]
J'ai fait un nouveau commit  avec une prise en compte des point demandé dans l'issue ! @StyveLioumba

**Comment by StyveLioumba** [comment]
> J'ai fait un nouveau commit  avec une prise en compte des point demandé dans l'issue ! @StyveLioumba 

Ça marche @benaja-bendo  , est ce que tu peux faire la revue Merci. 
Je vais également checker ça ce soir
