### ISSUE TITLE
Réalisations

### ISSUE THREAD

**Issue by benaja-bendo** [Technostrea/technostrea.com#3]
- [x] Lister les projets
- [x] Description des projets

**Comment by benaja-bendo** [comment]
@Copirighter707 @SOVIE9 
D'après vous sur le site que mettre comme projets sachant que pour l'instant nos projets sont en construction.

**Comment by Copirighter707** [comment]
On peut mêttre les projets en cours et dire en cours de réalisation a côté
en petit
