### ISSUE TITLE
Expertises

### ISSUE THREAD

**Issue by benaja-bendo** [Technostrea/technostrea.com#4]
- [x] Lister les domaines d'expertise
- [x] Phrase accrocheuse des expertise

**Comment by benaja-bendo** [comment]
## technologie back end
- Java
- Node js
- Php
- Kotlin

## technologie front end
- JavaScript vanille
- React js
- TypeScript
- Angular
- TaillwindCss
- Material UI

**Comment by StyveLioumba** [comment]
> ## technologie back end
> * Java
> * Node js
> * Php
> * Kotlin
> 
> ## technologie front end
> * JavaScript vanille
> * React js
> * TypeScript
> * Angular
> * TaillwindCss
> * Material UI

il ne faut pas que ca fasse comme un cv .
je pense qu'on peut faire par catégorie 

- développement de logiciels
- Infrastrure cloud
